// frameworks/non-keyed/vuera/src/App.vue
<template>
    <div class="container">
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-6">
                    <h1>Vuera v0.1.3 (non-keyed)</h1>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-sm-6 smallpad">
                          <button type="button" class="btn btn-primary btn-block" id="run" v-on:click="run">Create 1,000 rows</button>
                        </div>
                        <div class="col-sm-6 smallpad">
                            <button type="button" class="btn btn-primary btn-block" id="runlots" v-on:click="runLots">Create 10,000 rows</button>
                        </div>
                        <div class="col-sm-6 smallpad">
                            <button type="button" class="btn btn-primary btn-block" id="add" v-on:click="add">Append 1,000 rows</button>
                        </div>
                        <div class="col-sm-6 smallpad">
                            <button type="button" class="btn btn-primary btn-block" id="update" v-on:click="update">Update every 10th row</button>
                        </div>
                        <div class="col-sm-6 smallpad">
                            <button type="button" class="btn btn-primary btn-block" id="clear" v-on:click="clear">Clear</button>
                        </div>
                        <div class="col-sm-6 smallpad">
                            <button type="button" class="btn btn-primary btn-block" id="swaprows" v-on:click="swapRows">Swap Rows</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <table class="table table-hover table-striped test-data" @click="handleClick">
            <tbody>
                <tr v-for="item in rows" :class="{'danger': item.id == selected}">
                    <td class="col-md-1">{{item.id}}</td>
                    <td class="col-md-4">
                        <a data-action="select" :data-id="item.id">{{item.label}}</a>
                    </td>
                    <td class="col-md-1">
                        <a>
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"
                                data-action="remove" :data-id="item.id"></span>
                        </a>
                    </td>
                    <td class="col-md-6"></td>
                </tr>
            </tbody>
        </table>
        <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true"></span>
    </div>
</template>

<script>
// import { Store } from './store';
const {Store} = require('./Store');

var store = new Store();

export default {
    data: () => ({
        rows: store.data,
        selected: store.selected
    }),
    methods: {
        handleClick (e) {
            const { action, id } = e.target.dataset
            if (action && id) {
                this[action](id)
            }
        },
        add() {
            store.add();
            this.sync();
        },
        remove(id) {
            store.delete(id);
            this.sync();
        },
        select(id) {
            store.select(id);
            this.sync();
        },
        run() {
            store.run();
            this.sync();
        },
        update() {
            store.update();
            this.sync();
        },
        runLots() {
            store.runLots();
            this.sync();
        },
        clear() {
            store.clear();
            this.sync();
        },
        swapRows() {
            store.swapRows();
            this.sync();
        },
        sync() {
            this.rows = Object.freeze(store.data);
            this.selected = store.selected;
        }
    }
}
</script>

// frameworks/keyed/astro-solid-nanostores/src/App.jsx
import { useStore } from "@nanostores/solid";
import { For } from "solid-js";
import { rows, selectedId, run, runLots, add, update, clear, swapRows, removeRow, select } from "./store.js";

const Button = ([id, text, fn]) => (
  <div class="col-sm-6 smallpad">
    <button id={id} class="btn btn-primary btn-block" type="button" onClick={fn}>
      {text}
    </button>
  </div>
);

export default function App() {
  const $rows = useStore(rows);
  const $selectedId = useStore(selectedId);

  return (
    <div class="container">
      <div class="jumbotron">
        <div class="row">
          <div class="col-md-6">
            <h1>Astro-solid-nanostores-keyed</h1>
          </div>
          <div class="col-md-6">
            <div class="row">
              <Button {...["run", "Create 1,000 rows", run]} />
              <Button {...["runlots", "Create 10,000 rows", runLots]} />
              <Button {...["add", "Append 1,000 rows", add]} />
              <Button {...["update", "Update every 10th row", update]} />
              <Button {...["clear", "Clear", clear]} />
              <Button {...["swaprows", "Swap Rows", swapRows]} />
            </div>
          </div>
        </div>
      </div>
      <table class="table table-hover table-striped test-data">
        <tbody>
          <For each={$rows()}>
            {(item) => (
              <tr class={$selectedId() === item.id ? "danger" : ""}>
                <td class="col-md-1" textContent={item.id} />
                <td class="col-md-4">
                  <a onClick={() => select(item.id)} textContent={item.label} />
                </td>
                <td class="col-md-1">
                  <a onClick={() => removeRow(item.id)}>
                    <span class="glyphicon glyphicon-remove" aria-hidden="true" />
                  </a>
                </td>
                <td class="col-md-6" />
              </tr>
            )}
          </For>
        </tbody>
      </table>
      <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true" />
    </div>
  );
}
