// frameworks/keyed/angular-xsm/src/app/table/table.component.ts
import { Component } from '@angular/core';
import {get, set, bindState} from 'xsm'

interface Data {
    id: number;
    label: string;
}

@Component({
  styleUrls: ['../currentStyle.css'],
  selector: 'app-table',
  template: `
    <table class="table table-hover table-striped test-data">
        <tbody>
            <tr [class.danger]="item.id===selected" *ngFor="let item of rows; trackBy: itemById">
                <td class="col-md-1">{{item.id}}</td>
                <td class="col-md-4">
                    <a href="#" (click)="select(item, $event)">{{item.label}}</a>
                </td>
                <td class="col-md-1"><a href="#" (click)="delete(item, $event)"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
                <td class="col-md-6"></td>
            </tr>
        </tbody>
    </table>
`
})
export class TableComponent {
  selected: number = 0;
    // rows: {id: number, label: string}[] = [];
  rows: Array<Data> = [];

  constructor() {
      bindState(this, {rows: []});
  }

  itemById(index: number, item) {
      return item.id;
  }

  select(item, event: Event) {
      event.preventDefault();
      this.selected = item.id;
  }

  delete(item, event: Event) {
      event.preventDefault();
      let rows = get('rows');
      rows.splice(rows.indexOf(item), 1);
  }

}

<p>
  table works!
</p>

// frameworks/keyed/vue-xsm/src/table.vue
<template>
        <table class="table table-hover table-striped test-data">
            <tbody>
                <tr v-for="item in rows" :key="item.id" :class="{'danger': item.id == selected}">
                    <td class="col-md-1">{{item.id}}</td>
                    <td class="col-md-4">
                        <a @click="select" :data-id="item.id">{{item.label}}</a>
                    </td>
                    <td class="col-md-1">
                        <a>
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"
                                @click="remove" :data-id="item.id"></span>
                        </a>
                    </td>
                    <td class="col-md-6"></td>
                </tr>
            </tbody>
        </table>
</template>

<script>
import { startMeasure, stopMeasure } from './store';
import { get, set, bindState } from 'xsm';

export default {
    data: () => ({
        selected: 0
    }),
    created() {
        bindState(this,{rows: []});
    },
    methods: {
        remove(e) {
            let id = e.target.dataset.id;
            let rows = this.rows;
            const idx = rows.findIndex(d => d.id==id);
            let data = rows.slice(0, idx);
            data.push(...rows.slice(idx + 1));
            set('rows', data);
            e.stopPropagation();
        },
        select(e) {
            this.selected = e.target.dataset.id;
            e.stopPropagation();
        },
    }
}
</script>
