// frameworks/keyed/qwik/src/components/app/index.tsx
import { component$, useStore } from "@builder.io/qwik";

let idCounter = 1;
const adjectives = [
    "pretty",
    "large",
    "big",
    "small",
    "tall",
    "short",
    "long",
    "handsome",
    "plain",
    "quaint",
    "clean",
    "elegant",
    "easy",
    "angry",
    "crazy",
    "helpful",
    "mushy",
    "odd",
    "unsightly",
    "adorable",
    "important",
    "inexpensive",
    "cheap",
    "expensive",
    "fancy",
  ],
  colours = [
    "red",
    "yellow",
    "blue",
    "green",
    "pink",
    "brown",
    "purple",
    "brown",
    "white",
    "black",
    "orange",
  ],
  nouns = [
    "table",
    "chair",
    "house",
    "bbq",
    "desk",
    "car",
    "pony",
    "cookie",
    "sandwich",
    "burger",
    "pizza",
    "mouse",
    "keyboard",
  ];

function _random(max: number) {
  return Math.round(Math.random() * 1000) % max;
}

export function buildData(count: number) {
  let data = new Array(count);
  for (let i = 0; i < count; i++) {
    data[i] = {
      id: idCounter++,
      label: `${adjectives[_random(adjectives.length)]} ${
        colours[_random(colours.length)]
      } ${nouns[_random(nouns.length)]}`,
    };
  }
  return data;
}

export const Row = component$(
  ({
    item,
    state,
    isSelected,
  }: {
    item: BenchState["data"][0];
    state: BenchState;
    isSelected: boolean;
  }) => {
    const { id, label } = item;
    return (
      <tr class={isSelected ? "danger" : ""}>
        <td class="col-md-1">{item.id}</td>
        <td class="col-md-4">
          <a
            onClick$={() => {
              state.selected = id;
            }}
          >
            {label}
          </a>
        </td>
        <td class="col-md-1">
          <a
            onClick$={() => {
              const d = state.data;
              d.splice(
                d.findIndex((d) => d.id === id),
                1
              );
            }}
          >
            <span class="glyphicon glyphicon-remove" aria-hidden="true" />
          </a>
        </td>
        <td class="col-md-6" />
      </tr>
    );
  }
);

type BenchState = {
  data: Array<{ id: number; label: string }>;
  selected: number | null;
};
export const App = component$(() => {
  const state = useStore<BenchState>(
    { data: [], selected: null },
    { deep: true }
  );
  return (
    <div class="container">
      <div class="jumbotron">
        <div class="row">
          <div class="col-md-6">
            <h1>Qwik Keyed</h1>
          </div>
          <div class="col-md-6">
            <div class="row">
              <div class="col-sm-6 smallpad">
                <button
                  id="run"
                  class="btn btn-primary btn-block"
                  type="button"
                  onClick$={() => (state.data = buildData(1000))}
                >
                  Create 1,000 rows
                </button>
                <button
                  id="runlots"
                  class="btn btn-primary btn-block"
                  type="button"
                  onClick$={() => (state.data = buildData(10000))}
                >
                  Create 10,000 rows
                </button>
                <button
                  id="add"
                  class="btn btn-primary btn-block"
                  type="button"
                  onClick$={() => state.data.push(...buildData(1000))}
                >
                  Append 1,000 rows
                </button>
                <button
                  id="update"
                  class="btn btn-primary btn-block"
                  type="button"
                  onClick$={() => {
                    for (
                      let i = 0, d = state.data, len = d.length;
                      i < len;
                      i += 10
                    )
                      d[i].label += " !!!";
                  }}
                >
                  Update every 10th row
                </button>
                <button
                  id="clear"
                  class="btn btn-primary btn-block"
                  type="button"
                  onClick$={() => (state.data = [])}
                >
                  Clear
                </button>
                <button
                  id="swaprows"
                  class="btn btn-primary btn-block"
                  type="button"
                  onClick$={() => {
                    const d = state.data.slice();
                    if (d.length > 998) {
                      let tmp = d[1];
                      d[1] = d[998];
                      d[998] = tmp;
                      state.data = d;
                    }
                  }}
                >
                  Swap Rows
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <table class="table table-hover table-striped test-data">
        <tbody>
          {state.data.map((item) => (
            <Row
              key={item.id}
              item={item}
              state={state}
              isSelected={item.id === state.selected}
            />
          ))}
        </tbody>
      </table>
      <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true" />
    </div>
  );
});

// frameworks/keyed/astro-svelte/src/App.svelte
<script>
  let rowId = 1;
  let data = $state.raw([]);
  let selected = $state.raw();

  const adjectives = [
    "pretty",
    "large",
    "big",
    "small",
    "tall",
    "short",
    "long",
    "handsome",
    "plain",
    "quaint",
    "clean",
    "elegant",
    "easy",
    "angry",
    "crazy",
    "helpful",
    "mushy",
    "odd",
    "unsightly",
    "adorable",
    "important",
    "inexpensive",
    "cheap",
    "expensive",
    "fancy",
  ];
  const colours = ["red", "yellow", "blue", "green", "pink", "brown", "purple", "brown", "white", "black", "orange"];
  const nouns = [
    "table",
    "chair",
    "house",
    "bbq",
    "desk",
    "car",
    "pony",
    "cookie",
    "sandwich",
    "burger",
    "pizza",
    "mouse",
    "keyboard",
  ];

  function _random(max) {
    return Math.round(Math.random() * 1000) % max;
  }

  class Item {
    id = rowId++;
    label = $state.raw(
      `${adjectives[_random(adjectives.length)]} ${colours[_random(colours.length)]} ${nouns[_random(nouns.length)]}`
    );
  }

  function buildData(count = 1000) {
    const arr = new Array(count);
    for (let i = 0; i < count; i++) arr[i] = new Item();
    return arr;
  }

  const run = () => {
    data = buildData(1000);
    selected = undefined;
  };
  const runLots = () => {
    data = buildData(10000);
    selected = undefined;
  };
  const add = () => (data = [...data, ...buildData(1000)]);
  const clear = () => {
    data = [];
    selected = undefined;
  };
  const partialUpdate = () => {
    for (let i = 0; i < data.length; i += 10) data[i].label = data[i].label + " !!!";
  };
  const remove = (row) => {
    const clone = data.slice();
    clone.splice(clone.indexOf(row), 1);
    data = clone;
  };
  const swapRows = () => {
    if (data.length > 998) {
      const clone = data.slice();
      const tmp = clone[1];
      clone[1] = clone[998];
      clone[998] = tmp;
      data = clone;
    }
  };
</script>

<div class="container">
  <div class="jumbotron">
    <div class="row">
      <div class="col-md-6"><h1>Astro-svelte-keyed</h1></div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block" id="run" onclick={run}>Create 1,000 rows</button>
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block" id="runlots" onclick={runLots}
              >Create 10,000 rows</button
            >
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block" id="add" onclick={add}>Append 1,000 rows</button>
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block" id="update" onclick={partialUpdate}
              >Update every 10th row</button
            >
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block" id="clear" onclick={clear}>Clear</button>
          </div>
          <div class="col-sm-6 smallpad">
            <button type="button" class="btn btn-primary btn-block" id="swaprows" onclick={swapRows}>Swap Rows</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <table class="table table-hover table-striped test-data">
    <tbody>
      {#each data as row (row)}
        <tr class={selected === row.id ? "danger" : ""}
          ><td class="col-md-1">{row.id}</td><td class="col-md-4"
            ><a
              onclick={() => {
                selected = row.id;
              }}>{row.label}</a
            ></td
          ><td class="col-md-1"
            ><a onclick={() => remove(row)}><span class="glyphicon glyphicon-remove" aria-hidden="true" /></a></td
          ><td class="col-md-6" /></tr
        >
      {/each}
    </tbody>
  </table>
  <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true"></span>
</div>
