// frameworks/keyed/astro-solid-nanostores/src/App.jsx
import { useStore } from '@nanostores/solid';
import { For } from 'solid-js';
import { rows, selectedId, run, runLots, add, update, clear, swapRows, removeRow, select } from './store.js';

const Button = ([id, text, fn]) => (
  <div class="col-sm-6 smallpad">
    <button id={id} class="btn btn-primary btn-block" type="button" onClick={fn}>
      {text}
    </button>
  </div>
);

export default function App() {
  const $rows = useStore(rows);
  const $selectedId = useStore(selectedId);

  return (
    <div class="container">
      <div class="jumbotron">
        <div class="row">
          <div class="col-md-6"><h1>Astro Solid Nano Stores keyed</h1></div>
          <div class="col-md-6">
            <div class="row">
              <Button {...['run', 'Create 1,000 rows', run]} />
              <Button {...['runlots', 'Create 10,000 rows', runLots]} />
              <Button {...['add', 'Append 1,000 rows', add]} />
              <Button {...['update', 'Update every 10th row', update]} />
              <Button {...['clear', 'Clear', clear]} />
              <Button {...['swaprows', 'Swap Rows', swapRows]} />
            </div>
          </div>
        </div>
      </div>
      <table class="table table-hover table-striped test-data">
        <tbody>
          <For each={$rows()}>
            {(item) => (
              <tr class={$selectedId() === item.id ? 'danger' : ''}>
                <td class="col-md-1" textContent={item.id} />
                <td class="col-md-4">
                  <a onClick={() => select(item.id)} textContent={item.label} />
                </td>
                <td class="col-md-1">
                  <a onClick={() => removeRow(item.id)}>
                    <span class="glyphicon glyphicon-remove" aria-hidden="true" />
                  </a>
                </td>
                <td class="col-md-6" />
              </tr>
            )}
          </For>
        </tbody>
      </table>
      <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true" />
    </div>
  );
}

// frameworks/keyed/astro-vue-nanostores/src/App.vue
<script setup>
import { useStore } from '@nanostores/vue';
import { rows, selectedId, run, runLots, add, update, clear, swapRows, removeRow, select } from './store.js';

const $rows = useStore(rows);
const $selectedId = useStore(selectedId);
</script>

<template>
  <div class="container">
    <div class="jumbotron">
      <div class="row">
        <div class="col-md-6">
          <h1>Astro Vue Nano Stores keyed</h1>
        </div>
        <div class="col-md-6">
          <div class="row">
            <div class="col-sm-6 smallpad">
              <button type="button" class="btn btn-primary btn-block" id="run" @click="run">Create 1,000 rows</button>
            </div>
            <div class="col-sm-6 smallpad">
              <button type="button" class="btn btn-primary btn-block" id="runlots" @click="runLots">Create 10,000 rows</button>
            </div>
            <div class="col-sm-6 smallpad">
              <button type="button" class="btn btn-primary btn-block" id="add" @click="add">Append 1,000 rows</button>
            </div>
            <div class="col-sm-6 smallpad">
              <button type="button" class="btn btn-primary btn-block" id="update" @click="update">Update every 10th row</button>
            </div>
            <div class="col-sm-6 smallpad">
              <button type="button" class="btn btn-primary btn-block" id="clear" @click="clear">Clear</button>
            </div>
            <div class="col-sm-6 smallpad">
              <button type="button" class="btn btn-primary btn-block" id="swaprows" @click="swapRows">Swap Rows</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <table class="table table-hover table-striped test-data">
      <tbody>
        <tr
          v-for="item of $rows"
          :key="item.id"
          :class="{ danger: item.id === $selectedId }"
          v-memo="[item.label, item.id === $selectedId]"
        >
          <td class="col-md-1">{{ item.id }}</td>
          <td class="col-md-4"><a @click="select(item.id)">{{ item.label }}</a></td>
          <td class="col-md-1">
            <a @click="removeRow(item.id)">
              <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            </a>
          </td>
          <td class="col-md-6"></td>
        </tr>
      </tbody>
    </table>
    <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true"></span>
  </div>
</template>
