// frameworks/keyed/vue-vuex/src/table.vue
<template>
        <table class="table table-hover table-striped test-data">
            <tbody>
                <tr v-for="item in $store.getters.Rows" :key="item.id" :class="{'danger': item.id == selected}">
                    <td class="col-md-1">{{item.id}}</td>
                    <td class="col-md-4">
                        <a @click="select" :data-id="item.id">{{item.label}}</a>
                    </td>
                    <td class="col-md-1">
                        <a>
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"
                                @click="remove" :data-id="item.id"></span>
                        </a>
                    </td>
                    <td class="col-md-6"></td>
                </tr>
            </tbody>
        </table>
</template>

<script>

export default {
    data: () => ({
        selected: 0
    }),
    methods: {
        remove(e) {
            let id = e.target.dataset.id;
            let rows = this.$store.getters.Rows;
            const idx = rows.findIndex(d => d.id==id);
            let data = rows.slice(0, idx);
            data.push(...rows.slice(idx + 1));
            this.$store.commit('Rows', Object.freeze(data));
            e.stopPropagation();
        },
        select(e) {
            this.selected = e.target.dataset.id;
            e.stopPropagation();
        },
    }
}
</script>

// frameworks/keyed/lit-starbeam/src/table.ts
import { html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import { FormulaList } from "@starbeam/core";
import { cached } from "@starbeam/js";

import { starbeam } from "./integration";
import { Item, Table } from "./types";

@customElement('table-element')
export class TableElement extends LitElement {
  @property() table: Table;

  @cached
  get rows() {
    return FormulaList(this.table.data, {
      key: item => item.id,
      value: ({ id, label }) => {
        let isSelected = id === this.table.selected;
        let select = () => this.table.select(id);
        let remove = () => this.table.remove(id);

        return html`
          <tr id=${id} class=${isSelected ? 'danger' : ''}>
            <td class="col-md-1">${id}</td>
            <td class="col-md-4">
              <a @onClick=${select}>${label}</a>
            </td>
            <td class="col-md-1">
              <a @onClick=${remove}>
                <span class="glyphicon glyphicon-remove"aria-hidden="true"></span>
              </a>
            </td>
            <td class="col-md-6"></td>
          </tr>
        `;
      }
    });
  }

  @starbeam
  render() {
    return html`
      <table class="table table-hover table-striped test-data">
        <tbody>${this.rows.current}</tbody>
      </table>
    `
  };
}
