// etch-v0.12.5-non-keyed/src/Main.jsx
'use strict';
/** @jsx etch.dom */

var etch = require('etch');
const {Row} = require('./Row');
const {Store} = require('./Store');

var startTime;
var lastMeasure;
var startMeasure = function(name) {
    startTime = performance.now();
    lastMeasure = name;
}
var stopMeasure = function() {
    var last = lastMeasure;
    if (lastMeasure) {
        window.setTimeout(function () {
            lastMeasure = null;
            var stop = performance.now();
            var duration = 0;
            console.log(last+" took "+(stop-startTime));
        }, 0);
    }
}

export class Main {
    constructor(props, children) {
        this.props = props;
        this.children = children;

        this.store = new Store();

        this.select = this.select.bind(this);
        this.delete = this.delete.bind(this);
        this.add = this.add.bind(this);
        this.run = this.run.bind(this);
        this.updateRows = this.updateRows.bind(this);
        this.runLots = this.runLots.bind(this);
        this.clear = this.clear.bind(this);
        this.swapRows = this.swapRows.bind(this);

        etch.initialize(this);
    }

    update (props, children) {
        return etch.update(this).then(() => {
            stopMeasure();
        });
    }

    run() {
        startMeasure("run");
        this.store.run();
        this.update();
    }
    add() {
        startMeasure("add");
        this.store.add();
        this.update();
    }
    updateRows() {
        startMeasure("update");
        this.store.update();
        this.update();
    }
    select(id) {
        startMeasure("select");
        this.store.select(id);
        this.update();
    }
    delete(id) {
        startMeasure("delete");
        this.store.delete(id);
        this.update();
    }
    runLots() {
        startMeasure("runLots");
        this.store.runLots();
        this.update();
    }
    clear() {
        startMeasure("clear");
        this.store.clear();
        this.update();
    }
    swapRows() {
        startMeasure("swapRows");
        this.store.swapRows();
        this.update();
    }
    render () {
        let rows = this.store.data.map((d,i) => {
            return <Row key={i} data={d} onClick={this.select} onDelete={this.delete} styleClass={d.id === this.store.selected ? 'danger':''}></Row>
        });
        return (<div className="container">
            <div className="jumbotron">
                <div className="row">
                    <div className="col-md-6">
                        <h1>etch v0.12.5 (non-keyed)</h1>
                    </div>
                    <div className="col-md-6">
                        <div className="row">
                            <div className="col-sm-6 smallpad">
                                <button type="button" className="btn btn-primary btn-block" id="run" onClick={this.run}>Create 1,000 rows</button>
                            </div>
                            <div className="col-sm-6 smallpad">
                                <button type="button" className="btn btn-primary btn-block" id="runlots" onClick={this.runLots}>Create 10,000 rows</button>
                            </div>
                            <div className="col-sm-6 smallpad">
                                <button type="button" className="btn btn-primary btn-block" id="add" onClick={this.add}>Append 1,000 rows</button>
                            </div>
                            <div className="col-sm-6 smallpad">
                                <button type="button" className="btn btn-primary btn-block" id="update" onClick={this.updateRows}>Update every 10th row</button>
                            </div>
                            <div className="col-sm-6 smallpad">
                                <button type="button" className="btn btn-primary btn-block" id="clear" onClick={this.clear}>Clear</button>
                            </div>
                            <div className="col-sm-6 smallpad">
                                <button type="button" className="btn btn-primary btn-block" id="swaprows" onClick={this.swapRows}>Swap Rows</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <table className="table table-hover table-striped test-data">
                <tbody>
                    {rows}
                </tbody>
            </table>
            <span className="preloadicon glyphicon glyphicon-remove" aria-hidden="true"></span>
        </div>);
    }
}

// frameworks/non-keyed/lit/src/main.ts
import { LitElement, html } from "lit";
import { property, customElement } from "lit/decorators.js";
import { Store } from './store';

const store = new Store();

@customElement('main-element')
export class MainElement extends LitElement {
    @property()
    _rows = store.data;

    @property()
    _selected = store.selected;

    render() {
        return html`
        <link href="/css/currentStyle.css" rel="stylesheet"/>
        <div class="container">
            <div class="jumbotron">
                <div class="row">
                    <div class="col-md-6">
                        <h1>Lit non-keyed</h1>
                    </div>
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-sm-6 smallpad">
                            <button type="button" class="btn btn-primary btn-block" id="run" @click=${this._run}>Create 1,000 rows</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="runlots" @click=${this._runLots}>Create 10,000 rows</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="add" @click=${this._add}>Append 1,000 rows</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="update" @click=${this._update}>Update every 10th row</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="clear" @click=${this._clear}>Clear</button>
                            </div>
                            <div class="col-sm-6 smallpad">
                                <button type="button" class="btn btn-primary btn-block" id="swaprows" @click=${this._swapRows}>Swap Rows</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-hover table-striped test-data" @click=${this._handleClick}>
                <tbody>${this._rows.map(item => html`
                <tr id=${item.id} class=${this._selected == item.id ? 'danger' : ''}>
                    <td class="col-md-1">${item.id}</td>
                    <td class="col-md-4">
                    <a data-action="select" data-id=${item.id}>${item.label}</a>
                    </td>
                    <td class="col-md-1">
                    <a>
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"
                            data-action="remove" data-id=${item.id}></span>
                    </a>
                    </td>
                    <td class="col-md-6"></td>
                </tr>`)}
                </tbody>
            </table>
            <span class="preloadicon glyphicon glyphicon-remove" aria-hidden="true"></span>
        </div>
        `;
    }

    _handleClick(e) {
        const { action, id } = e.target.dataset
        if (action && id) {
            this['_' + action](id)
        }
    }
    _add() {
        store.add();
        this._sync();
    }
    _remove(id) {
        store.delete(id);
        this._sync();
    }
    _select(id) {
        store.select(id);
        this._sync();
    }
    _run() {
        store.run();
        this._sync();
    }
    _update() {
        store.update();
        this._sync();
    }
    _runLots() {
        store.runLots();
        this._sync();
    }
    _clear() {
        store.clear();
        this._sync();
    }
    _swapRows() {
        store.swapRows();
        this._sync();
    }
    _sync() {
        this._rows = store.data;
        this._selected = store.selected;
    }
}
